### ISSUE TITLE
Lost signal

### ISSUE THREAD

**Issue by xellDart** [nathanchance/gcc-prebuilts#1]
using this toolchain i lost the ril
* huawei p8 lite hisi6220 *none logs

**Comment by nathanchance** [comment]
Well that's a super descriptive issue... Doesn't sound like an actual toolchain issue, considering I have no issues. I don't assist with debugging device specific issues that come about from using these. But I will ask this, using this toolchain to compile what? Kernel? ROM?

**Comment by xellDart** [comment]
An apology, I am compiling a kernel for p8 lite, with the toolchain <5 the RIL works properly, but> 5, the ril stops working ....

**Comment by kondors1995** [comment]
How did you compiled hole rom ussing this tc?
