### ISSUE TITLE
-Wformat-truncation gcc-7 snprintf

### ISSUE THREAD

**Issue by ac130kz** [nathanchance/gcc-prebuilts#2]
Probably, the problem should not be presented to you directly, but when I try to build my LineageOS kernel for m8, I get truncation warning and the process stops. I already did a research on it and found that gcc-7 should be blamed for this and it was probably patched. I don't know how to resolve the problem, could you help me with this?

[Building process](https://pastebin.com/7UmZyCrV)
[clock-debug.c](https://pastebin.com/58g0TH5Q)

I also found a cool flag to solve this -Wno-format-truncation, but I don't know where to add it...

**Comment by nathanchance** [comment]
https://github.com/nathanchance/op5/commit/3dbc00881dddff4673c73ee66f5c42550137b55e

Those warnings aren't worth fixing.
